# Changes here will be overwritten by Copier
_commit: f72f50f
_src_path: .
copyright_year: '2026'
documentation: false
email: cuinixam@gmail.com
full_name: cuinixam
github_username: cuinixam
package_name: spl_west_deps
project_name: spl-west-deps
project_short_description: An spl-core build extension that installs the west dependencies
    of a variant
project_slug: spl-west-deps
